<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19045.0</TargetPlatformMinVersion>
    <SupportedOSPlatformVersion>10.0.19045.0</SupportedOSPlatformVersion>
    <Platforms>AnyCPU;x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <SelfContained>true</SelfContained>
    <PublishSelfContained>true</PublishSelfContained>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <UseDotNetNativeToolchain>false</UseDotNetNativeToolchain>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Openza.Flow</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <GenerateAppxPackageOnBuild>false</GenerateAppxPackageOnBuild>
    <GenerateAppInstallerFile>False</GenerateAppInstallerFile>
    <AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
    <AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
    <GenerateTestArtifacts>False</GenerateTestArtifacts>
    <AppxSymbolPackageEnabled>false</AppxSymbolPackageEnabled>
    <AppxBundle>Never</AppxBundle>
    <HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
  </PropertyGroup>

  <PropertyGroup>
    <LocalPackageCertificateKeyFile>Openza.Flow_TemporaryKey.pfx</LocalPackageCertificateKeyFile>
    <LocalPackageSigningEnabled Condition="'$(LocalPackageSigningEnabled)' == ''">false</LocalPackageSigningEnabled>
    <AppxPackageSigningEnabled Condition="'$(LocalPackageSigningEnabled)' == 'true' and Exists('$(LocalPackageCertificateKeyFile)')">true</AppxPackageSigningEnabled>
    <AppxPackageSigningEnabled Condition="'$(LocalPackageSigningEnabled)' != 'true' or !Exists('$(LocalPackageCertificateKeyFile)')">false</AppxPackageSigningEnabled>
    <PackageCertificateKeyFile Condition="'$(LocalPackageSigningEnabled)' == 'true' and Exists('$(LocalPackageCertificateKeyFile)')">$(LocalPackageCertificateKeyFile)</PackageCertificateKeyFile>
    <GenerateTemporaryStoreCertificate>True</GenerateTemporaryStoreCertificate>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.WindowsDesktop.App.WindowsForms" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Openza.Flow.Core\Openza.Flow.Core.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <AppxManifest Include="Package.Dev.appxmanifest" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' != 'Debug'">
    <AppxManifest Include="Package.appxmanifest" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\*.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\*.ico" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Package.appxmanifest" />
    <None Include="Package.Dev.appxmanifest" />
  </ItemGroup>

  <Target Name="DisableStoreUploadPackagingForCommandLineBuild" BeforeTargets="_GenerateAppxUploadPackageRecipe;_GenerateAppxUploadPackageFile;_CreateAppStoreContainerForUAP;GenerateUploadMsixPackage" Condition="'$(BuildingInsideVisualStudio)' != 'true' and '$(GenerateAppxPackageOnBuild)' != 'true' and '$(PublishAppxPackage)' != 'true'">
    <PropertyGroup>
      <BuildAppxUploadPackageForUap>false</BuildAppxUploadPackageForUap>
    </PropertyGroup>
  </Target>
</Project>
